### ISSUE TITLE
Use Vega-Embed

### ISSUE THREAD

**Issue by domoritz** [observablehq/vega#8]
Vega-Embed adds links to the editor and adds some simple customizations. I started some experiments at https://beta.observablehq.com/@domoritz/vega-embed-observable-package-experiments but got stuck with two things

1. I can't figure out how to return the Vega view and the dom element (https://github.com/observablehq/vega/issues/1)
2. I would prefer to load Vega, Vega-Lite, and Vega-Embed separately, but I couldn't see a way to specify the dependency chain. See https://talk.observablehq.com/t/update-requirejs-config/592/3

This would fix https://github.com/observablehq/vega/pull/7 as well and could address #6 if we add tooltips to Vega-Embed.

**Comment by mbostock** [comment]
1\. You can use `viewof` to expose both the Vega View and the DOM element.

2\. Seems like you already got it working in another notebook, but since Vega-Embed doesn’t declare its dependencies on Vega and Vega-Lite, you need to require them separately and bind them to the globals that Vega-Embed expects.

Here’s my take:

https://beta.observablehq.com/@mbostock/hello-vega-embed

**Comment by domoritz** [comment]
Thank you @mbostock! I will look into `viewof`.

Re embed. I had something similar working in https://beta.observablehq.com/@domoritz/vega-lite-demo-with-vega-embed but I don't know how to replicate this in a module that uses `define`. 


I tried something like 

```
define(["vega@3", "vega-lite@2"], function(Vega, VegaLite) {
  window.vega = Vega;
  window.vl = VegaLite;

  // obviously doesn't work
  define(["vega-embed@3"], function(VegaEmbed)) {
    return function vegalite(spec, options) {
      ...
    };
  };
});
```

and 

```
define(["vega@3", "vega-lite@2"], function(Vega, VegaLite) {
  window.vega = Vega;
  window.vl = VegaLite;

  vegaEmbed = require("vega-embed@3");  // doesn't work because require is async

  return function vegalite(spec, options) {
    ...
  };
});
```

Any hints?

**Comment by mbostock** [comment]
Right, I don’t think you can do this in d3-require now: d3-require requires you to know the dependencies ahead of time and resolves them in parallel. There’s not currently a way to have a “late-binding” dependency that loads after the rest of the modules.

I can think of a few ways to fix this.

The first one—and the *right* fix, in my opinion—is to have Vega-Embed declare its dependencies on vega and vega-lite. In AMD, the Vega-Embed definition should look something like this (assuming only a default export of the *embed* function):

```js
define(["vega", "vega-lite"], function() {
  return async function embed(el, spec, opt) {
    …
  };
});
```

The UMD implementation is slightly more complicated (see [d3-geo](https://unpkg.com/d3-geo@1.10.0/dist/d3-geo.js) for example), but boils down to the same thing. I don’t know how to do this with Browserify, but I’d guess that it’s possible; I’m much more familiar with Rollup, and I highly recommend it. (Rollup has a [Typescript plugin](https://github.com/rollup/rollup-plugin-typescript), too.)

The second fix would be to add support for dynamic `require` in d3-require. Then you could define your Observable wrapper for vega-embed as follows:

```js
define(["require", "vega", "vega-lite"], async function(require, Vega, VegaLite) {
  window.vega = Vega;
  window.vl = VegaLite;
  const ve = await require("vega-embed");
  return async function(spec, options) {
    const div = document.createElement("div");
    div.value = await ve(div, spec, options);
    return div;
  };
});
```

This would work, but I’m not wild about it because `require` in AMD (CommonJS) is synchronous, whereas the implementation that could be provided by d3-require is necessarily asynchronous. Adding support for dynamic `require` in d3-require would only be useful for people writing AMD’s specifically for d3-require… which should hopefully be no one, as new libraries should be published as ES modules!

A third option would be to recommend an Observable import instead of publishing a library to npm:

```js
import {vega} from "@mbostock/hello-vega-embed"
```

If you want to target Observable explicitly, that seems like a reasonable option. But I still think declaring your dependencies and adopting Rollup is your best bet in the long term—it’d let you also publish an ES module, for example.

**Comment by domoritz** [comment]
We are using browserify for Vega-Embed right now but I think it makes sense to switch over to rollup and declare the dependencies properly. I will look into that!

In the meantime, I've added support for viewof to my prototype at https://beta.observablehq.com/@domoritz/vega-embed-observable-package-experiments.

**Comment by mbostock** [comment]
Looks great!

**Comment by domoritz** [comment]
Now I'm wondering: when we switch Vega-Embed to AMD and depend on both Vega and Vega-Lite, we will always load Vega-Lite, even if we only need Vega. Do you see a simple way to avoid that or do we need to create two bundles? As I understand it, requirejs's [shim configuration](http://requirejs.org/docs/api.html#config-shim) was designed to address this issue for shimmed libraries and would apply in embed's case. I don't see a way to solve this with d3-require. Maybe it doesn't matter since Vega-Lite is small but just something I noticed.
